/*
 * File: RequestController.java
 *
 * Description: REST controller for handling request-related HTTP requests.
 *              Provides endpoints for creating, retrieving, updating, and soft-deleting requests.
 *              Supports pagination and sorting for listing requests.
 *              Includes Swagger annotations for API documentation.
 *
 * Author: Generated by Grok (based on input from Kabera Clapton)
 * Last Modified: 2025-07-29
 */
package rw.ac.ilpd.notificationservice.controller;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import rw.ac.ilpd.notificationservice.service.RequestService;
import rw.ac.ilpd.sharedlibrary.dto.request.RequestCommentRequest;
import rw.ac.ilpd.sharedlibrary.dto.request.RequestRequest;
import rw.ac.ilpd.sharedlibrary.dto.request.RequestResponse;
import rw.ac.ilpd.sharedlibrary.dto.request.UserRequestApprovalRequest;

import java.util.UUID;

@Tag(name = "Requests", description = "API for managing requests in the ILPD MIS")
@RestController
@RequestMapping("/requests")
@RequiredArgsConstructor
@Slf4j
public class RequestController
{

    private final RequestService requestService;

    @Operation(
            summary = "Create a new request",
            description = "Creates a new request with the provided details, including optional comments, attachments, and approvals."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Request created successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "404", description = "Referenced request type not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PostMapping
    public ResponseEntity<RequestResponse> createRequest(
            @Valid @RequestBody RequestRequest request)
    {
        log.info("Received request to create request with content: {}", request.getContent());
        RequestResponse response = requestService.createRequest(request);
        return new ResponseEntity<>(response, HttpStatus.CREATED);
    }

    @Operation(
            summary = "Retrieve a request by ID",
            description = "Fetches a request by its unique ID, excluding soft-deleted requests."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Request retrieved successfully"),
            @ApiResponse(responseCode = "404", description = "Request not found or is deleted"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/{id}")
    public ResponseEntity<RequestResponse> getRequestById(
            @Parameter(description = "ID of the request to retrieve") @PathVariable String id)
    {
        log.info("Received request to retrieve request with ID: {}", id);
        RequestResponse response = requestService.getRequestById(id);
        return ResponseEntity.ok(response);
    }

    @Operation(
            summary = "Retrieve all requests",
            description = "Fetches a paginated and sorted list of non-deleted requests."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Requests retrieved successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid pagination or sorting parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping
    public ResponseEntity<Page<RequestResponse>> getAllRequests(
            @Parameter(description = "Page number (0-based)", example = "0") @RequestParam(defaultValue = "0") int page,
            @Parameter(description = "Number of items per page", example = "10") @RequestParam(defaultValue = "10") int size,
            @Parameter(description = "Field to sort by", example = "createdAt") @RequestParam(defaultValue = "createdAt") String sortBy,
            @Parameter(description = "Sort direction (asc or desc)", example = "desc") @RequestParam(defaultValue = "desc") String order)
    {
        log.info("Received request to retrieve all requests with page: {}, size: {}, sortBy: {}, order: {}",
                page, size, sortBy, order);
        Page<RequestResponse> response = requestService.getAllRequests(page, size, sortBy, order);
        return ResponseEntity.ok(response);
    }

    @Operation(
            summary = "Retrieve requests by user ID",
            description = "Fetches a paginated and sorted list of non-deleted requests created by a specific user."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Requests retrieved successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid pagination or sorting parameters"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @GetMapping("/user/{userId}")
    public ResponseEntity<Page<RequestResponse>> getRequestsByUserId(
            @Parameter(description = "ID of the user whose requests are to be retrieved")
            @PathVariable UUID userId,
            @Parameter(description = "Page number (0-based)", example = "0")
            @RequestParam(defaultValue = "0") int page,
            @Parameter(description = "Number of items per page", example = "10")
            @RequestParam(defaultValue = "10") int size,
            @Parameter(description = "Field to sort by", example = "createdAt")
            @RequestParam(defaultValue = "createdAt") String sortBy,
            @Parameter(description = "Sort direction (asc or desc)", example = "desc")
            @RequestParam(defaultValue = "desc") String order)
    {
        log.info("Received request to retrieve requests for user ID: {} with page: {}, size: {}, sortBy: {}, order: {}",
                userId, page, size, sortBy, order);
        Page<RequestResponse> response = requestService.getRequestsByUserId(userId, page, size, sortBy, order);
        return ResponseEntity.ok(response);
    }

    @Operation(
            summary = "Update an existing request",
            description = "Updates the details of an existing request by its ID, including optional comments, attachments, and approvals."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "200", description = "Request updated successfully"),
            @ApiResponse(responseCode = "400", description = "Invalid request data"),
            @ApiResponse(responseCode = "404", description = "Request not found or is deleted"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PutMapping("/{id}")
    public ResponseEntity<RequestResponse> updateRequest(
            @Parameter(description = "ID of the request to update") @PathVariable String id,
            @Valid @RequestBody RequestRequest request)
    {
        log.info("Received request to update request with ID: {}", id);
        RequestResponse response = requestService.updateRequest(id, request);
        return ResponseEntity.ok(response);
    }

    @Operation(
            summary = "Soft-delete a request",
            description = "Marks a request as deleted by setting isDeleted to true."
    )
    @ApiResponses({
            @ApiResponse(responseCode = "204", description = "Request soft-deleted successfully"),
            @ApiResponse(responseCode = "404", description = "Request not found or is already deleted"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @DeleteMapping("/{id}")
    public ResponseEntity<Void> deleteRequest(
            @Parameter(description = "ID of the request to soft-delete") @PathVariable String id)
    {
        log.info("Received request to soft-delete request with ID: {}", id);
        requestService.deleteRequest(id);
        return ResponseEntity.noContent().build();
    }

    @Operation(
            summary = "Add a comment to a request",
            description = "Allows an authorized user to add a comment to a request"
    )
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Comment added successfully"),
            @ApiResponse(responseCode = "404", description = "Request to comment not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PostMapping("/{id}/comments")
    public ResponseEntity<RequestResponse> addComment(
            @Parameter(description = "ID of the request to retrieve") @PathVariable String id,
            @Valid @RequestBody RequestCommentRequest comment)
    {
        log.info("Received request to add a comment to a request with ID: {}", id);
        return new ResponseEntity<>(requestService.addComment(id, comment), HttpStatus.CREATED);
    }

    @Operation(
            summary = "Approve or reject a request",
            description = "Allows an authorized user to approve or reject a request"
    )
    @ApiResponses({
            @ApiResponse(responseCode = "201", description = "Approval or rejection effected successfully"),
            @ApiResponse(responseCode = "404", description = "Request to approve or reject not found"),
            @ApiResponse(responseCode = "500", description = "Internal server error")
    })
    @PostMapping("/{id}/approvals")
    public ResponseEntity<RequestResponse> approveRejectRequest(
            @Parameter(description = "ID of the request to retrieve") @PathVariable String id,
            @Valid @RequestBody UserRequestApprovalRequest userRequestApprovalRequest)
    {
        log.info("Received request to add a comment to a request with ID: {}", id);
        return new ResponseEntity<>(requestService.approveRejectRequest(id, userRequestApprovalRequest),
                HttpStatus.CREATED);
    }
}