/*
* HostelRoomResponse.java
*
* Authors: Kabera Clapton(ckabera6@gmail.com)
*
* This dto is an abstraction of the HostelRoom entity.
* */
package rw.ac.ilpd.mis.shared.dto.hostel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import rw.ac.ilpd.mis.shared.enums.HostelRoomStatus;
import rw.ac.ilpd.mis.shared.enums.RoomStatusState;

import java.time.LocalDateTime;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelRoomResponse {
    // this is generated by the system
//    private String id;
//
//    // this should be pre-existing in the system
//    private String roomNumber;
//    private String hostelRoomType;
//    private String status;
//
//    // this is generated in the system
//    private String createdAt;
    private String id;
    private String roomNumber;
    private String roomTypeId;
    private HostelRoomStatus occupationStatus;
    private RoomStatusState roomStatusState;
    private LocalDateTime createdAt;
}
