/*
 * HostelReservationRoomTypeCountResponse.java
 *
 * Authors: Kabera Clapton(ckabera6@gmail.com)
 *
 * This dto is an abstraction of the HostelReservationRoomTypeCount entity.
 * */
package rw.ac.ilpd.mis.shared.dto.hostel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelReservationRoomTypeCountResponse {
    // This is generated by the system
//    private String id;
//    private String hostelReservation;
//    private String reservationRoomType;
//    private int numberOfRooms;
    private String id ;
    private String hostelReservationId;
    private String roomTypeId;
    private int numberOfRooms;
    // this is generated by the system
    private String createdAt;
}

