/*
* HostelReservationRoomResponse.java
*
* Authors: Kabera Clapton(ckabera6@gmail.com)
*
* This dto is an abstraction of the HostelReservationRoom entity.
* */
package rw.ac.ilpd.mis.shared.dto.hostel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelReservationRoomResponse {
//    // This is generated by the system
//    private String id;
//
//    // am not sure if we need this field since we already have the reservation UUID
//    private String reservationCode;
//    private String reservation;
//    private String reservedRoom;
//
//    // not sure if we need this field too since it is also captured in the
//    // reservation table which
//    // has a relationship to the ExternalUser entity which is the client.
//    private String client;
//    private Double actualPrice;
//
//    private String checkInTime;
//    private String checkOutTime;
//
//    // this is generated by the system.
//    private String createdAt;
    private String id;
    private String reservationCode;
    private String reservation;
    private String room;
    private String client;
    private BigDecimal actualPrice;
    private String checkInTime;
    private String checkOutTime;
    private String createdAt;
    private String updatedAt;
}
