/*
* HostelReservationResponse.java
*
* Authors: Kabera Clapton(ckabera6@gmail.com)
*
* This dto is an abstraction of the HostelReservation entity.
* */
package rw.ac.ilpd.sharedlibrary.dto.hostel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;


import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelReservationResponse {
    // this is generated by the system
    private String id;
    private String externalUser;
    private int numberOfPeople;
    private String arrivalDate;
    private String departureDate;
    private int monthsToSpend;
    private int numberOfRooms;

    // random_query_code in the ERD. It is generated by the system.
    private String randomQueryCode;
    private String reservationType;
    private String reservationStatus;

//    private List<String> hostelReservationRooms;
    private List<HostelReservationRoomTypeCountResponse>hostelReservationRoomTypeCounts;
    // Generated by the system
    private String createdAt;
}
