/*
 * HostelRoomImageResponse.java
 *
 * Authors: Kabera Clapton(ckabera6@gmail.com)
 *
 * This dto is an abstraction of the HostelRoomImageResponse entity.
 * */
package rw.ac.ilpd.sharedlibrary.dto.hostel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelRoomImageResponse {
    // this is generated by the system
    private String id;
//    private String roomType;
    private String imageDocId;
    private String url;
}
