/*
* HostelReservationRoomPaymentResponse.java
*
* Authors: Kabera Clapton(ckabera6@gmail.com)
*
* This dto is an abstraction of the HostelReservationRoomPaymentResponse entity
* */
package rw.ac.ilpd.sharedlibrary.dto.hostel;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import rw.ac.ilpd.sharedlibrary.dto.payment.PaymentDocumentResponse;
import rw.ac.ilpd.sharedlibrary.enums.PaymentMethod;
import rw.ac.ilpd.sharedlibrary.enums.PaymentStatus;

import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.List;
import java.util.UUID;


@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelReservationRoomPaymentResponse {
//    // this is generated by the system
//    private String id;
//    private String reservedRoom;
//    private Double amount;
//
//    // This is created in the system
//    private String createdAt;
//
//    private String proofOfPaymentDoc;
//    private String paymentMethod;

    private String id;
    private BigDecimal amount;
    private String transactionNumber;
    private UUID creditAccountId; //referencing setting table
    private String paymentMethod;
    private String paymentStatus;
    private String createdAt;
    private String updatedAt;
    private List<PaymentDocumentResponse> paymentDocuments;
}
