/*
* HostelReservationRequest.java
*
* Authors: Kabera Clapton(ckabera6@gmail.com)
*
* This dto is an abstraction of the HostelReservation entity.
* */
package rw.ac.ilpd.sharedlibrary.dto.hostel;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import rw.ac.ilpd.sharedlibrary.dto.validation.RestrictedString;


import java.time.LocalDateTime;
import java.util.List;

@Data
@AllArgsConstructor
@NoArgsConstructor
@Builder
public class HostelReservationRequest {

    @NotNull(message = "The externalUser cannot be null")
    private String externalUser;

    @Positive(message = "The numberOfPeople cannot have a negative value")
    private int numberOfPeople;

    @NotNull(message = "The arrivalDate cannot be null")
    @FutureOrPresent(message = "You cannot reserve a room and arrive in the past")
    private LocalDateTime arrivalDate;

    @NotNull(message = "The departureDate cannot be null")
    @Future(message = "Your departure date has to be in the future")
    private LocalDateTime departureDate;

    @Positive(message = "You cannot spend negative months in the hostel")
    private int monthsToSpend;

    @NotNull(message = "The numberOfRooms cannot be null")
    @Positive(message = "You cannot reserve a negative number of rooms")
    private int numberOfRooms;

    // random_query_code in the ERD. It is generated by the system.
    private String randomQueryCode;

    //    @NotNull(message = "The reservationType cannot be null")
    private String reservationType;
    //    @NotNull(message = "The reservationStatus cannot be null")
    private String reservationStatus;
    private List<HostelReservationRoomTypeCountRequest> hostelReservationRoomTypeCounts;
//    private List<String> hostelReservationRooms;
}
