/*
 * File: NotificationTypeService.java
 *
 * Description: Service class for handling business logic related to notification types.
 *              Provides methods for creating, retrieving, updating, and deleting notification types.
 *              Includes pagination and sorting for listing notification types.
 *
 * Author: Generated by Grok (based on input from Kabera Clapton)
 * Last Modified: 2025-07-29
 */
package rw.ac.ilpd.notificationservice.service;

import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import rw.ac.ilpd.notificationservice.model.nosql.document.NotificationType;
import rw.ac.ilpd.notificationservice.repository.nosql.NotificationTypeRepository;
import rw.ac.ilpd.notificationservice.mapper.NotificationTypeMapper;
import rw.ac.ilpd.sharedlibrary.dto.notification.NotificationTypeRequest;
import rw.ac.ilpd.sharedlibrary.dto.notification.NotificationTypeResponse;
import rw.ac.ilpd.sharedlibrary.enums.NotificationTypeEnum;

@Service
@RequiredArgsConstructor
@Slf4j
public class NotificationTypeService
{

    private final NotificationTypeRepository notificationTypeRepository;
    private final NotificationTypeMapper notificationTypeMapper;

    /**
     * Creates a new notification type from the provided request DTO.
     *
     * @param request The notification type request DTO
     * @return The created notification type response DTO
     * @throws IllegalArgumentException if the request is invalid
     */
    public NotificationTypeResponse createNotificationType(NotificationTypeRequest request)
    {
        log.info("Creating notification type with name: {}", request.getName());
        NotificationType notificationType = notificationTypeMapper.toNotificationType(request);
        NotificationType savedNotificationType = notificationTypeRepository.save(notificationType);
        log.debug("Notification type created successfully with ID: {}", savedNotificationType.getId());
        return notificationTypeMapper.fromNotificationType(savedNotificationType);
    }

    /**
     * Retrieves a notification type by its ID.
     *
     * @param id The ID of the notification type
     * @return The notification type response DTO
     * @throws EntityNotFoundException() if the notification type is not found
     */
    public NotificationTypeResponse getNotificationTypeById(String id)
    {
        log.info("Retrieving notification type with ID: {}", id);
        NotificationType notificationType = notificationTypeRepository.findById(id)
                .orElseThrow(() ->
                {
                    log.error("Notification type with ID {} not found", id);
                    return new EntityNotFoundException("Notification type with ID " + id + " not found");
                });
        return notificationTypeMapper.fromNotificationType(notificationType);
    }

    /**
     * Retrieves a paginated and sorted list of notification types.
     *
     * @param page    The page number (0-based)
     * @param size    The page size
     * @param sortBy  The field to sort by
     * @param sortDir The sort direction (asc or desc)
     * @return A page of notification type response DTOs
     */
    public Page<NotificationTypeResponse> getAllNotificationTypes(int page, int size, String sortBy, String sortDir)
    {
        log.info("Retrieving notification types with page: {}, size: {}, sortBy: {}, sortDir: {}"
                , page, size, sortBy, sortDir);

        Sort sort = Sort.by(sortDir.equalsIgnoreCase("asc")
                ? Sort.Direction.ASC
                : Sort.Direction.DESC, sortBy);

        Pageable pageable = PageRequest.of(page, size, sort);
        Page<NotificationType> notificationTypes = notificationTypeRepository.findAll(pageable);
        return notificationTypes.map(notificationTypeMapper::fromNotificationType);
    }

    /**
     * Updates an existing notification type.
     *
     * @param id      The ID of the notification type to update
     * @param request The updated notification type request DTO
     * @return The updated notification type response DTO
     * @throws EntityNotFoundException if the notification type is not found
     */
    public NotificationTypeResponse updateNotificationType(String id, NotificationTypeRequest request)
    {
        log.info("Updating notification type with ID: {}", id);
        NotificationType existingNotificationType = notificationTypeRepository.findById(id)
                .orElseThrow(() ->
                {
                    log.error("Notification type with ID {} not found", id);
                    return new EntityNotFoundException("Notification type with ID " + id + " not found");
                });

        existingNotificationType.setName(request.getName());
        NotificationType updatedNotificationType = notificationTypeRepository.save(existingNotificationType);
        log.debug("Notification type updated successfully with ID: {}", updatedNotificationType.getId());

        return notificationTypeMapper.fromNotificationType(updatedNotificationType);
    }

    /**
     * Deletes a notification type by its ID.
     *
     * @param id The ID of the notification type to delete
     * @throws EntityNotFoundException if the notification type is not found
     */
    public boolean deleteNotificationType(String id)
    {
        log.info("Deleting notification type with ID: {}", id);
        if (!notificationTypeRepository.existsById(id))
        {
            log.error("Notification type with ID {} not found", id);
            throw new EntityNotFoundException("Notification type with ID " + id + " not found");
        }

        notificationTypeRepository.deleteById(id);
        log.debug("Notification type deleted successfully with ID: {}", id);
        return true;
    }
}