/*
 * File: TemplateService.java
 *
 * Description: Service class for handling business logic related to templates.
 *              Provides methods for creating, retrieving, updating, soft-deleting, and listing templates.
 *              Includes pagination and sorting for listing templates, with filtering for active templates if specified.
 *
 * Author: Generated by Grok (based on input from Kabera Clapton)
 * Last Modified: 2025-07-30
 */
package rw.ac.ilpd.notificationservice.service;

import jakarta.persistence.EntityNotFoundException;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.stereotype.Service;
import rw.ac.ilpd.notificationservice.mapper.DocumentMapper;
import rw.ac.ilpd.notificationservice.mapper.TemplateMapper;
import rw.ac.ilpd.notificationservice.model.nosql.document.Template;
import rw.ac.ilpd.notificationservice.repository.nosql.TemplateRepository;
import rw.ac.ilpd.sharedlibrary.dto.document.TemplateRequest;
import rw.ac.ilpd.sharedlibrary.dto.document.TemplateResponse;

@Service
@RequiredArgsConstructor
@Slf4j
public class TemplateService
{
    private final TemplateRepository templateRepository;
    private final TemplateMapper templateMapper;
    private final DocumentMapper documentMapper;

    /**
     * Creates a new template from the provided request DTO.
     *
     * @param request The template request DTO
     * @return The created template response DTO
     * @throws IllegalArgumentException if the request is invalid
     */
    public TemplateResponse createTemplate(TemplateRequest request)
    {
        log.info("Creating template with name: {}", request.getName());
        Template template = templateMapper.toTemplate(request);
        Template savedTemplate = templateRepository.save(template);
        log.debug("Template created successfully with ID: {}", savedTemplate.getId());
        return templateMapper.fromTemplate(savedTemplate);
    }

    /**
     * Retrieves a template by its ID.
     *
     * @param id The ID of the template
     * @return The template response DTO
     * @throws EntityNotFoundException() if the template is not found
     */
    public TemplateResponse getTemplateById(String id)
    {
        log.info("Retrieving template with ID: {}", id);
        Template template = templateRepository.findByIdAndIsActiveTrue(id)
                .orElseThrow(() ->
                {
                    log.error("Template with ID {} not found", id);
                    return new EntityNotFoundException("Template with ID " + id + " not found");
                });
        return templateMapper.fromTemplate(template);
    }

    /**
     * Retrieves a paginated and sorted list of templates, optionally filtered by isActive.
     *
     * @param page     The page number (0-based)
     * @param size     The page size
     * @param sortBy   The field to sort by
     * @param sortDir  The sort direction (asc or desc)
     * @return A page of template response DTOs
     */
    public Page<TemplateResponse> getAllTemplates(int page, int size, String sortBy, String sortDir)
    {
        log.info("Retrieving templates with page: {}, size: {}, sortBy: {}, sortDir: {}",
                page, size, sortBy, sortDir);
        Sort sort = Sort.by(sortDir.equalsIgnoreCase("asc") ? Sort.Direction.ASC : Sort.Direction.DESC, sortBy);
        Pageable pageable = PageRequest.of(page, size, sort);
        Page<Template> templates = templateRepository.findByIsActiveTrue(pageable);
        return templates.map(templateMapper::fromTemplate);
    }

    /**
     * Updates an existing template.
     *
     * @param id      The ID of the template to update
     * @param request The updated template request DTO
     * @return The updated template response DTO
     * @throws EntityNotFoundException() if the template is not found
     */
    public TemplateResponse updateTemplate(String id, TemplateRequest request)
    {
        log.info("Updating template with ID: {}", id);
        Template existingTemplate = templateRepository.findById(id)
                .orElseThrow(() ->
                {
                    log.error("Template with ID {} not found", id);
                    return new EntityNotFoundException("Template with ID " + id + " not found");
                });

        existingTemplate.setName(request.getName());
        existingTemplate.setDocument(documentMapper.toDocumentMIS(request.getDocument()));
        existingTemplate.setIsActive(request.getIsActive());

        Template updatedTemplate = templateRepository.save(existingTemplate);
        log.debug("Template updated successfully with ID: {}", updatedTemplate.getId());
        return templateMapper.fromTemplate(updatedTemplate);
    }

    /**
     * Soft-deletes a template by setting isActive to false.
     *
     * @param id The ID of the template to soft-delete
     * @throws EntityNotFoundException if the template is not found
     */
    public void deleteTemplate(String id)
    {
        log.info("Soft-deleting template with ID: {}", id);
        Template template = templateRepository.findById(id)
                .orElseThrow(() ->
                {
                    log.error("Template with ID {} not found", id);
                    return new EntityNotFoundException("Template with ID " + id + " not found");
                });
        template.setIsActive(false);
        templateRepository.save(template);
        log.debug("Template soft-deleted successfully with ID: {}", id);
    }
}